version: '3.8'

services:
  table-rag:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "8501:8501"  # Streamlit port
      - "11434:11434"  # Ollama port
    volumes:
      - ollama-models:/root/.ollama  # Persist Ollama models
    environment:
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama-models: